### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by aindilis** [mukesh-mehta/SemEval2020-Task6#1]
Your system looks useful.  Could you please provide some instructions how to run on Linux?

**Comment by mukesh-mehta** [comment]
Hi aindilis, 

sorry for very late response, I was busy with my examination. 
Following are the steps you can follow to run this code, I will update this in the repository also.
1. clone the repository
2. clone the dataset and helper functions from https://github.com/adobe-research/deft_corpus repository. (try to follow the same directory structure)
3. conda env create -f environment.yml
4. source activate semeval
5. go to deft_corpus directory and run following commands
   mkdir deft_corpus/data/Task1/train deft_corpus/data/Task1/dev 
   python task1_converter.py 'data/deft_files/train/' 'data/Task1/train/'
   python task1_converter.py 'data/deft_files/dev/' 'data/Task1/dev/'
6. go to src
   python task1_bert_finetune.py

will add more detail in Readme of the repo.
